### PR TITLE
tuning scalar multiplication 

### PR DESCRIPTION
**Pull request by kalmarek**
@blegat

### CODE REVIEW

**Comment by blegat** [comment]
It's maybe cleaner to do something like
```julia
"""
    lmul(a, X)
Multiplies the coefficients of `X` by `a`.
"""
function lmul end
function lmul(a, X::AlgebraElement)
    return MA.operate_to(similar(X), lmul, a, X)
end
Base.:*(a, X::AlgebraEleemnt) = lmul(a, X)
```
where `lmul` would be an explicit way to multiply the coefficients (I'm open to other names, in MP, I call it `left_constant_mult` I think)

**Comment by kalmarek** [comment]
I'm not sure it changes much, I don't intend these functions to be used by anyone outside ;)

**Comment by kalmarek** [comment]
> It's maybe cleaner to do something like
> 
> ```julia
> """
>     lmul(a, X)
> Multiplies the coefficients of `X` by `a`.
> """
> function lmul end
> function lmul(a, X::AlgebraElement)
>     return MA.operate_to(similar(X), lmul, a, X)
> end
> Base.:*(a, X::AlgebraEleemnt) = lmul(a, X)
> ```
> 
> where `lmul` would be an explicit way to multiply the coefficients (I'm open to other names, in MP, I call it `left_constant_mult` I think but we don't have to use the same name)

It serves precisely the opposite role, where the coefficients stay the same and we shift keys ;)

**Review by blegat — APPROVED** [review]
There is some added allocation on nightly but it might be due to a change in Julia since yesterday

**Comment by kalmarek** [comment]
Since you approved, fixing nightly is on you from now on :D

**Pull request merged**
